site_name: NWChem
repo_url: https://github.com/nwchemgit/nwchem-wiki
edit_uri: blob/master/
theme:
  name: readthedocs
  prev_next_buttons_location: both
use_directory_urls: false
markdown_extensions:
    - smarty
    - toc
plugins:
  - search
  - alternate-link
nav:
      - Documentation: Home.md
      - Download: Download.md
      - Quantum-Mechanical-Methods.md
      - Quantum-Molecular-Dynamics.md
      - Other-Capabilities.md
      - Examples.md
      - Supplementary-Information.md
      - Compiling-NWChem.md
      - Benchmarks.md
      - Tutorials.md
      - Forum.md
      - Archived Forum: Archived-Forum.md
